// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.CompileModules.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Logic.Security;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Framework.Security
{

    public class SecurityController : Controller
    {

        ///<summary>Retrieve all security definitions in the system</summary>
        ///<remarks>Used during initialization to populate SecurityUtil with data</remarks>
        ///<returns>List of security definitions</returns>
        [HttpPost]
        [Route("Framework/Security/FetchDefinitions")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<string> FetchDefinitions()
        {
            return SecurityLogic.FetchDefinitions();
        }

        ///<summary>Retrieve all security permissions for the current user</summary>
        ///<returns>List of security keys and access levels</returns>
        [HttpPost]
        [Route("Framework/Security/FetchPermissions")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<System.Tuple<string, FACTS.Framework.Security.SecurityAccess>> FetchPermissions()
        {
            return SecurityLogic.FetchPermissions();
        }

    }

}
