// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.CompileModules.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Framework.Lookup
{

    public static class LookupProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Framework/Lookup";

        ///<summary>ASYNC Web Service call: Retrieve all lookup names, codes and data in the system</summary>
        ///<remarks>Used during initialization to populate LookupUtil with data</remarks>
        ///<returns>ASYNC task: List of lookup names, codes and data</returns>
        public static async Task<System.Collections.Generic.Dictionary<string, FACTS.Framework.Lookup.LookupName>> FetchLookupsAsync()
        {
            using (OperationClient client = new OperationClient(servicePath, "FetchLookups"))
            {
                return await client.ReadAsync<System.Collections.Generic.Dictionary<string, FACTS.Framework.Lookup.LookupName>>();
            }
        }

        ///<summary>Web Service call: Retrieve all lookup names, codes and data in the system</summary>
        ///<remarks>Used during initialization to populate LookupUtil with data</remarks>
        ///<returns>List of lookup names, codes and data</returns>
        public static System.Collections.Generic.Dictionary<string, FACTS.Framework.Lookup.LookupName> FetchLookups()
        {
            return FetchLookupsAsync().Result;
        }

    }

}
