// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Core.Admin.DateTimeOffset
{

    public static class DateTimeOffsetProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Core/Admin/DateTimeOffset";

        ///<summary>ASYNC Web Service call: unknown</summary>
        public static async Task SetOffsetAsync(string name, double offset)
        {
            using (OperationClient client = new OperationClient(servicePath, "SetOffset"))
            {
                client.Value = new { name, offset };
                await client.SendAsync();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static void SetOffset(string name, double offset)
        {
            SetOffsetAsync(name, offset).Wait();
        }

    }

}
