// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Core.Admin.DateTimeOffset
{

    public class DateTimeOffsetController : Controller
    {

        ///<summary>Composite object for passing in multiple values to SetOffset method</summary>
        public class SetOffsetRequest
        {
            public string Name;
            public double Offset;
        }

        ///<param name="request">Composite request object for passing in multiple values</param>
        [HttpPost]
        [Route("Core/Admin/DateTimeOffset/SetOffset")]
        [OperationMethodFilter]
        public void SetOffset([FromBody]SetOffsetRequest request)
        {
            PFML.BusinessLogic.Core.Admin.DateTimeOffset.DateTimeOffsetLogic.SetOffset(request.Name, request.Offset);
        }

    }

}
