// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.CompileModules.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Logic.Lookup;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Framework.Lookup
{

    public class LookupController : Controller
    {

        ///<summary>Retrieve all lookup names, codes and data in the system</summary>
        ///<remarks>Used during initialization to populate LookupUtil with data</remarks>
        ///<returns>List of lookup names, codes and data</returns>
        [HttpPost]
        [Route("Framework/Lookup/FetchLookups")]
        [OperationMethodFilter]
        public System.Collections.Generic.Dictionary<string, FACTS.Framework.Lookup.LookupName> FetchLookups()
        {
            return LookupLogic.FetchLookups();
        }

    }

}
